after-startup-command = ["layout accordion"]

start-at-login = true

accordion-padding = 0

default-root-container-layout = 'accordion'
default-root-container-orientation = 'auto'

[gaps.inner]
horizontal = 0
vertical = 0

[gaps.outer]
left = 0
bottom = 0
top = 0
right = 0

[mode.main.binding]
alt-shift-semicolon = 'mode service'

[mode.service.binding]
esc = ['reload-config', 'mode main']
r = ['flatten-workspace-tree', 'mode main'] # reset layout
backspace = ['close-all-windows-but-current', 'mode main']
comma = 'layout accordion'

